{{- if .Values.configMap.create -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  namespace: {{ .Release.Namespace }}
data:
  VERBOSE: {{ .Values.configMap.env.verbose | default "false" | quote }}
  DEBUG: {{ .Values.configMap.env.debug  | default "false" | quote }}
  NAMESPACE: {{ .Values.configMap.env.namespace | default "default" | quote }}
  LIVENESS: {{ .Values.configMap.env.liveness | default "true" | quote }}
  LOOP_INTERVAL: {{ .Values.configMap.env.loop_interval | default 60 | quote }}
  EXCLUDED_NAMESPACES: {{ .Values.configMap.env.excluded_namespaces | default "kube-system,kube-public,kube-node-lease" | quote }}
{{- end }} 