apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-operator
  namespace: project-operator
  labels:
    app: project-operator
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: project-operator
  template:
    metadata:
      labels:
        app: project-operator
    spec:
      serviceAccountName: project-operator
      securityContext:
        runAsUser:
          1000
      containers:
      - envFrom:
          - configMapRef:
              name: project-operator
        name: op
        image: djkormo/project-operator:0.0.5
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - all
          privileged: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
