apiVersion: v1
kind: LimitRange
metadata:
  name: "{name}"
  namespace: "{name}"
spec:
  limits:
  - max:
      memory: "{maxmem}"
      cpu: "{maxcpu}"
    min:
      cpu: "{mincpu}"
      memory: "{minmem}"
    default:
      cpu: "{defaultcpu}"
      memory: "{defaultmem}"
    defaultRequest:
      cpu: "{defaultrequestcpu}"
      memory: "{defaultrequestmem}"
    type: Container